[package]
name = "wasm-tiny-template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['cdylib']
name = 'output'

[profile.release]
opt-level = 3
lto = true
tell = 0.1

[build]
target = "wasm32-unknown-unknown"

[dependencies]
nanoserde = "*"
